/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DirectoryRouteRouteImport } from './routes/directory/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapIndexRouteImport } from './routes/map/index'
import { Route as wwwSitemapDotxmlRouteImport } from './routes/(www)/sitemap[.]xml'
import { Route as wwwInfoRouteImport } from './routes/(www)/info'
import { Route as wwwHomeRouteImport } from './routes/(www)/home'
import { Route as DirectoryIdIndexRouteImport } from './routes/directory/$id/index'

const DirectoryRouteRoute = DirectoryRouteRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => rootRouteImport,
} as any)
const wwwSitemapDotxmlRoute = wwwSitemapDotxmlRouteImport.update({
  id: '/(www)/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const wwwInfoRoute = wwwInfoRouteImport.update({
  id: '/(www)/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const wwwHomeRoute = wwwHomeRouteImport.update({
  id: '/(www)/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryIdIndexRoute = DirectoryIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => DirectoryRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/directory': typeof DirectoryRouteRouteWithChildren
  '/home': typeof wwwHomeRoute
  '/info': typeof wwwInfoRoute
  '/sitemap.xml': typeof wwwSitemapDotxmlRoute
  '/map': typeof MapIndexRoute
  '/directory/$id': typeof DirectoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/directory': typeof DirectoryRouteRouteWithChildren
  '/home': typeof wwwHomeRoute
  '/info': typeof wwwInfoRoute
  '/sitemap.xml': typeof wwwSitemapDotxmlRoute
  '/map': typeof MapIndexRoute
  '/directory/$id': typeof DirectoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/directory': typeof DirectoryRouteRouteWithChildren
  '/(www)/home': typeof wwwHomeRoute
  '/(www)/info': typeof wwwInfoRoute
  '/(www)/sitemap.xml': typeof wwwSitemapDotxmlRoute
  '/map/': typeof MapIndexRoute
  '/directory/$id/': typeof DirectoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/directory'
    | '/home'
    | '/info'
    | '/sitemap.xml'
    | '/map'
    | '/directory/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/directory'
    | '/home'
    | '/info'
    | '/sitemap.xml'
    | '/map'
    | '/directory/$id'
  id:
    | '__root__'
    | '/'
    | '/directory'
    | '/(www)/home'
    | '/(www)/info'
    | '/(www)/sitemap.xml'
    | '/map/'
    | '/directory/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DirectoryRouteRoute: typeof DirectoryRouteRouteWithChildren
  wwwHomeRoute: typeof wwwHomeRoute
  wwwInfoRoute: typeof wwwInfoRoute
  wwwSitemapDotxmlRoute: typeof wwwSitemapDotxmlRoute
  MapIndexRoute: typeof MapIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/': {
      id: '/map/'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(www)/sitemap.xml': {
      id: '/(www)/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof wwwSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(www)/info': {
      id: '/(www)/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof wwwInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(www)/home': {
      id: '/(www)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof wwwHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/$id/': {
      id: '/directory/$id/'
      path: '/$id'
      fullPath: '/directory/$id'
      preLoaderRoute: typeof DirectoryIdIndexRouteImport
      parentRoute: typeof DirectoryRouteRoute
    }
  }
}

interface DirectoryRouteRouteChildren {
  DirectoryIdIndexRoute: typeof DirectoryIdIndexRoute
}

const DirectoryRouteRouteChildren: DirectoryRouteRouteChildren = {
  DirectoryIdIndexRoute: DirectoryIdIndexRoute,
}

const DirectoryRouteRouteWithChildren = DirectoryRouteRoute._addFileChildren(
  DirectoryRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DirectoryRouteRoute: DirectoryRouteRouteWithChildren,
  wwwHomeRoute: wwwHomeRoute,
  wwwInfoRoute: wwwInfoRoute,
  wwwSitemapDotxmlRoute: wwwSitemapDotxmlRoute,
  MapIndexRoute: MapIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
